theme: Minima
title: Document Archive for Planning and Transport
description: A site to store old planning and transport documents. By <a href="https://philipmallis.com">Philip Mallis</a>.
permalink: /:categories/:title
show_excerpts: true
baseurl: /archive

## Vanity
github_username: philam
flickr_username: philipmallis
rss: rss
    
## De-Americanising
date_format: "%-d %b %Y"
