theme: Minima
title: Document Archive
description: A site to store old planning and transport documents. By [Philip Mallis](https://philipmallis.com).
permalink: /:categories/:title
show_excerpts: true

## Vanity
minima:
  social_links:
    twitter: philipmallis
    github: philam
    flickr: philipmallis
    youtube: philipmallis
    youtube_channel: UC72AJxecUNtw2weOtdM-sdA
    youtube_channel_name: Philip Mallis
