theme: Minima
title: Document Archive for Planning and Transport
description: A site to store old planning and transport documents. By [Philip Mallis](https://philipmallis.com).
permalink: /:categories/:title
show_excerpts: true
baseurl: /archive

## Vanity
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/philam" }
    - { platform: flickr, user_url: "https://flickr.com/philipmallis" }
    - { platform: youtube, user_url: "https://youtube.com/philipmallis" }
    
## De-Americanising
minima:
  date_format: "%-d %b %Y"
